#call-site-mode: true

sources:
#  - { kind: call, method: "<Server: java.lang.String getInput()>", index: "result.value[*]" }
  - { kind: call, method: "<Server: char taint()>", index: "result" }

sinks:
  - { method: "<javax.script.ScriptEngine: java.lang.Object eval(java.lang.String)>", index: "0.value[*]" }
  - { method: "<javax.script.AbstractScriptEngine: java.lang.Object eval(java.lang.String)>", index: "0.value[*]" }
#  - { method: "<org.apache.commons.text.lookup.ScriptStringLookup: java.lang.String lookup(java.lang.String)>", index: "0.value[*]" }
# - { method: "<org.apache.commons.text.lookup.ScriptStringLookup: java.lang.String lookup(java.lang.String)>", index: 0 }
#  - { method: "<javax.script.ScriptEngineManager: javax.script.ScriptEngine getEngineByName(java.lang.String)>", index: 0 }

transfers:
  # - { method: "<java.lang.String: void getChars(int,int,char[],int)>", from: base, to: 2, type: "char[]" }
  # - { method: "<java.lang.String: void <init>(char[],int,int)>", from: 0, to: base, type: "java.lang.String" }
